language: node_js
node_js:
- 6
- node
sudo: false
cache:
  directories:
  - node_modules
services:
- postgresql
- redis-server
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- psql -c 'create database jkitchen;' -U postgres
- npm install -g istanbul sequelize sequelize-cli
script:
- istanbul cover ./node_modules/mocha/bin/_mocha tests/**/*.js --report lcovonly --
  -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  && rm -rf ./coverage
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: BCTIe5jfDjWwGjeZSJvx6fKs/bfXLR35hco+LTJ/OkvuYZb0CsL1Y1GrmWR456l3F1hoS9KeVBCF7wQuHh/AFWoB3TNPOyyquoN5Pc9kY7YuW3+MYpmcKk2kmm2uJTR6OFFlss17ku5HSbF1yOeoESdObfbPa8uqSP6KbXSubkFPQmR5i89LSMP24qPAtKAPzBdAFoCPdq/4W9aShN9nLLj29X/0sl5XEyQnqTnn/6dfrAzQTyRKcmmdPy23IFhQqrBmPCnqpM6Tdq7vw4k+RmhY4D7zYpSsZRlNpJ5W1tZIR3ToKSuw3nFXbe6lQsHm2zts0JUVuiuYMhLu6M1P6dsLvoODAIptVzjWzcItqB8/iZWxVm3JuvsE+qdEK4e2CRbg20LCk97GAfp+r6MHYyhagXdU92SovMycQMyP/EjTgvC+ULB0xwZ94WVkfpZpoydODUFOMb25Gu7yGie0mpZFKhQ38VjEKkIUqiRwjY9ocTrR0Et8wAb/faKYOVPjN2yaYOvp9qtCqI8XqC4yz7xWc9u6bZFQQqu8gjshw5+fErYKJljTj1c2MwX/HOj2vkpH1NsddhB4YziSlW8I1E8KTNG8kJ6SlHINMzRKL0gnwFZC6zwVyuJlRO9DTTnF1bQjNGwwFCOoyASrN72DKp7Z8yYIHUB53cq5I8YO198=
  app: jkitchenAPI
  on:
    repo: andela-joladimeji/jkitchenAPI
    branch: master
