language: node_js
node_js:
- 6
- node
sudo: false
cache:
  directories:
  - node_modules
services:
- postgresql
- redis-server
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- psql -c 'create database jkitchen;' -U postgres
- npm install -g istanbul sequelize sequelize-cli
script:
- istanbul cover ./node_modules/mocha/bin/_mocha tests/**/*.js --report lcovonly
  -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  && rm -rf ./coverage

